services:
  - type: web
    name: strike-vector-demo
    env: docker
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GOOGLE_CLIENT_ID
        value: 419308259695-sj14gj8q7ml5o9uao2j59pgkp1vvthh0.apps.googleusercontent.com
      - key: DATABASE_URL
        value: sqlite:///./demo_cloud.db
